### ISSUE TITLE
Warn Users of Trailing Whitespace

### ISSUE THREAD

**Issue by NathanSpeidel** [bullet-db/bullet-ui#64]
When adding a filter, all trailing whitespace in the value entered by the user is currently sent to the backend.

Because of this, users can easily unintentionally send an incorrect filter.  For example, a user might try to add a filter "id"="ke8dj21nd", but accidentally send the trailing whitespace to the backend:  "id"="ke8dj21nd     "

When filters have trailing (or prepending?) whitespace the UI should warn them about this to ensure it is intentional. 

This can be done with either a popup? Or maybe an exclamation-mark icon that appears next to the field with a description that appears when a user mouses-over the icon.

**Comment by akshaisarma** [comment]
I think this is too specific for particular data feeds to have to be part of the bullet-ui. Perhaps for some data sets, trailing spaces are normal... We can think about how to allow particular instances of the UI to customize such validations
